# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/red/CLionProjects/redis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/red/CLionProjects/redis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/red/CLionProjects/redis/CMakeFiles /Users/red/CLionProjects/redis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/red/CLionProjects/redis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named redis-cli

# Build rule for target.
redis-cli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 redis-cli
.PHONY : redis-cli

# fast build rule for target.
redis-cli/fast:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/build
.PHONY : redis-cli/fast

#=============================================================================
# Target rules for targets named redis-server

# Build rule for target.
redis-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 redis-server
.PHONY : redis-server

# fast build rule for target.
redis-server/fast:
	$(MAKE) -f CMakeFiles/redis-server.dir/build.make CMakeFiles/redis-server.dir/build
.PHONY : redis-server/fast

#=============================================================================
# Target rules for targets named hiredis

# Build rule for target.
hiredis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hiredis
.PHONY : hiredis

# fast build rule for target.
hiredis/fast:
	$(MAKE) -f deps/hiredis/CMakeFiles/hiredis.dir/build.make deps/hiredis/CMakeFiles/hiredis.dir/build
.PHONY : hiredis/fast

#=============================================================================
# Target rules for targets named linenoise

# Build rule for target.
linenoise: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linenoise
.PHONY : linenoise

# fast build rule for target.
linenoise/fast:
	$(MAKE) -f deps/linenoise/CMakeFiles/linenoise.dir/build.make deps/linenoise/CMakeFiles/linenoise.dir/build
.PHONY : linenoise/fast

#=============================================================================
# Target rules for targets named lua

# Build rule for target.
lua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lua
.PHONY : lua

# fast build rule for target.
lua/fast:
	$(MAKE) -f deps/lua/CMakeFiles/lua.dir/build.make deps/lua/CMakeFiles/lua.dir/build
.PHONY : lua/fast

#=============================================================================
# Target rules for targets named testmodule

# Build rule for target.
testmodule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testmodule
.PHONY : testmodule

# fast build rule for target.
testmodule/fast:
	$(MAKE) -f src/modules/CMakeFiles/testmodule.dir/build.make src/modules/CMakeFiles/testmodule.dir/build
.PHONY : testmodule/fast

#=============================================================================
# Target rules for targets named helloblock

# Build rule for target.
helloblock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloblock
.PHONY : helloblock

# fast build rule for target.
helloblock/fast:
	$(MAKE) -f src/modules/CMakeFiles/helloblock.dir/build.make src/modules/CMakeFiles/helloblock.dir/build
.PHONY : helloblock/fast

#=============================================================================
# Target rules for targets named hellotype

# Build rule for target.
hellotype: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hellotype
.PHONY : hellotype

# fast build rule for target.
hellotype/fast:
	$(MAKE) -f src/modules/CMakeFiles/hellotype.dir/build.make src/modules/CMakeFiles/hellotype.dir/build
.PHONY : hellotype/fast

#=============================================================================
# Target rules for targets named helloworld

# Build rule for target.
helloworld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloworld
.PHONY : helloworld

# fast build rule for target.
helloworld/fast:
	$(MAKE) -f src/modules/CMakeFiles/helloworld.dir/build.make src/modules/CMakeFiles/helloworld.dir/build
.PHONY : helloworld/fast

src/adlist.o: src/adlist.c.o

.PHONY : src/adlist.o

# target to build an object file
src/adlist.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/adlist.c.o
.PHONY : src/adlist.c.o

src/adlist.i: src/adlist.c.i

.PHONY : src/adlist.i

# target to preprocess a source file
src/adlist.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/adlist.c.i
.PHONY : src/adlist.c.i

src/adlist.s: src/adlist.c.s

.PHONY : src/adlist.s

# target to generate assembly for a file
src/adlist.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/adlist.c.s
.PHONY : src/adlist.c.s

src/ae.o: src/ae.c.o

.PHONY : src/ae.o

# target to build an object file
src/ae.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/ae.c.o
.PHONY : src/ae.c.o

src/ae.i: src/ae.c.i

.PHONY : src/ae.i

# target to preprocess a source file
src/ae.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/ae.c.i
.PHONY : src/ae.c.i

src/ae.s: src/ae.c.s

.PHONY : src/ae.s

# target to generate assembly for a file
src/ae.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/ae.c.s
.PHONY : src/ae.c.s

src/anet.o: src/anet.c.o

.PHONY : src/anet.o

# target to build an object file
src/anet.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/anet.c.o
.PHONY : src/anet.c.o

src/anet.i: src/anet.c.i

.PHONY : src/anet.i

# target to preprocess a source file
src/anet.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/anet.c.i
.PHONY : src/anet.c.i

src/anet.s: src/anet.c.s

.PHONY : src/anet.s

# target to generate assembly for a file
src/anet.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/anet.c.s
.PHONY : src/anet.c.s

src/crc64.o: src/crc64.c.o

.PHONY : src/crc64.o

# target to build an object file
src/crc64.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/crc64.c.o
.PHONY : src/crc64.c.o

src/crc64.i: src/crc64.c.i

.PHONY : src/crc64.i

# target to preprocess a source file
src/crc64.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/crc64.c.i
.PHONY : src/crc64.c.i

src/crc64.s: src/crc64.c.s

.PHONY : src/crc64.s

# target to generate assembly for a file
src/crc64.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/crc64.c.s
.PHONY : src/crc64.c.s

src/redis-cli.o: src/redis-cli.c.o

.PHONY : src/redis-cli.o

# target to build an object file
src/redis-cli.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/redis-cli.c.o
.PHONY : src/redis-cli.c.o

src/redis-cli.i: src/redis-cli.c.i

.PHONY : src/redis-cli.i

# target to preprocess a source file
src/redis-cli.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/redis-cli.c.i
.PHONY : src/redis-cli.c.i

src/redis-cli.s: src/redis-cli.c.s

.PHONY : src/redis-cli.s

# target to generate assembly for a file
src/redis-cli.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/redis-cli.c.s
.PHONY : src/redis-cli.c.s

src/release.o: src/release.c.o

.PHONY : src/release.o

# target to build an object file
src/release.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/release.c.o
.PHONY : src/release.c.o

src/release.i: src/release.c.i

.PHONY : src/release.i

# target to preprocess a source file
src/release.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/release.c.i
.PHONY : src/release.c.i

src/release.s: src/release.c.s

.PHONY : src/release.s

# target to generate assembly for a file
src/release.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/release.c.s
.PHONY : src/release.c.s

src/sds.o: src/sds.c.o

.PHONY : src/sds.o

# target to build an object file
src/sds.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/sds.c.o
.PHONY : src/sds.c.o

src/sds.i: src/sds.c.i

.PHONY : src/sds.i

# target to preprocess a source file
src/sds.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/sds.c.i
.PHONY : src/sds.c.i

src/sds.s: src/sds.c.s

.PHONY : src/sds.s

# target to generate assembly for a file
src/sds.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/sds.c.s
.PHONY : src/sds.c.s

src/zmalloc.o: src/zmalloc.c.o

.PHONY : src/zmalloc.o

# target to build an object file
src/zmalloc.c.o:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/zmalloc.c.o
.PHONY : src/zmalloc.c.o

src/zmalloc.i: src/zmalloc.c.i

.PHONY : src/zmalloc.i

# target to preprocess a source file
src/zmalloc.c.i:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/zmalloc.c.i
.PHONY : src/zmalloc.c.i

src/zmalloc.s: src/zmalloc.c.s

.PHONY : src/zmalloc.s

# target to generate assembly for a file
src/zmalloc.c.s:
	$(MAKE) -f CMakeFiles/redis-cli.dir/build.make CMakeFiles/redis-cli.dir/src/zmalloc.c.s
.PHONY : src/zmalloc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... redis-cli"
	@echo "... redis-server"
	@echo "... hiredis"
	@echo "... linenoise"
	@echo "... lua"
	@echo "... testmodule"
	@echo "... helloblock"
	@echo "... hellotype"
	@echo "... helloworld"
	@echo "... src/adlist.o"
	@echo "... src/adlist.i"
	@echo "... src/adlist.s"
	@echo "... src/ae.o"
	@echo "... src/ae.i"
	@echo "... src/ae.s"
	@echo "... src/anet.o"
	@echo "... src/anet.i"
	@echo "... src/anet.s"
	@echo "... src/crc64.o"
	@echo "... src/crc64.i"
	@echo "... src/crc64.s"
	@echo "... src/redis-cli.o"
	@echo "... src/redis-cli.i"
	@echo "... src/redis-cli.s"
	@echo "... src/release.o"
	@echo "... src/release.i"
	@echo "... src/release.s"
	@echo "... src/sds.o"
	@echo "... src/sds.i"
	@echo "... src/sds.s"
	@echo "... src/zmalloc.o"
	@echo "... src/zmalloc.i"
	@echo "... src/zmalloc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

